### ISSUE TITLE
Feature: User can view the weather of a location

### ISSUE THREAD

**Issue by Katelyn-Ngo** [Katelyn-Huong/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the weather of a location
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the weather of a location they desire by typing in the search bar
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-06-18 at 10 53 06 PM](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/0102efd5-4bf0-4252-a883-6339475b1e55)

![Screen Shot 2024-06-19 at 9 26 00 AM](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/e94f3e33-ba9c-42c8-b916-e0c4b8caa0ac)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Creat CSS styling
- [x] Add a 'div[data-view='weather-app'] to HTML
    - [x] Create a form to add a submit button for fetching the weather data
    - [x] add an input field for the location
   
- [x] Ensure form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make inputs of search 'required'

- [x] Get API key
    - [x] define a function to make an API call using the location input value
    - [x] Handle errors gracefully(ex: invalid location/API errors)
   
- [x] Listen for 'submit' events on form 
     - [x] Prevent default form submission behavior
     - [x] Get the value of the location input field
     - [x] Fetch weather data from weather API based on the input location
     - [x] Parse the fetched weather data
     - [x] Display the current weather data in the weather display section
    
- [x] Make sure to use swap view to direct users to a new view after they search for weather. 
      - [ ] get value of 'data-view' attribute of weather app and put in a variable
      - [ ] Loop through a Nodelist of elements and compare each of their 'data-view' attributes values to the declared variable in previous step. 
      - [ ] other views should be '.hidden' except the one that has a 'data-view' attribute that equals to the variable declared in previous step.  
    
- [x] Ensure weather data updates dynamically without refreshing the page
- [x] Reset input field after fetching the weather data

   
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
