### ISSUE TITLE
Feature: User can favorite location(s)

### ISSUE THREAD

**Issue by Katelyn-Ngo** [Katelyn-Huong/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite location(s)
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can favorite locations to conveniently view them. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-06-18 at 11 50 59 PM](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/f32c063d-5ca6-4b67-ab86-3944969f8e8f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure favorite icon and favorite location sections are responsive and looks good on both mobile and desktop sized screens. 

- [ ] Event Handling
   - [ ] Listen for clicks on the parent element of all rendered locations
   - [ ] Toggle the favorite location if the favorite icon was clicked
   - [ ] update favorite icon to visually show that location was favorited (red heart) 
 - [ ] Data Model
    - [ ] Update data model to include a favorites arrays for storing favorite locations
    - [ ] create local storage to save favorite locations in data.ts
    - [ ] in `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [ ] At the bottom of `data.js`, include a conditional statement that:
  - [ ] checks to see if there is a JSON data model stored in `localStorage`.
  - [ ] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
          - [ ]   attached event listener to object and listen for the beforeunload event
          - [ ] create callback function to stringify the favorites array 
          - [ ] store key/value pair to localStorage containing the JSON string
          - [ ] access localStroage using key name and assign the return result to a variable

- [ ] Form submission for new locations
     - [ ] Make sure form's input values are used to fetch weather data for a new location
     - [ ] add the new location to the rendered locations list and the data model
     - [ ] include the favorite icon for the new location
-
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Katelyn-Huong** [comment]
![Recording 2024-06-25 at 09 20 52](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/40502c39-a672-401f-918b-428d36e265f7)
