### ISSUE TITLE
Feature: User can view their favorite location(s)

### ISSUE THREAD

**Issue by Katelyn-Ngo** [Katelyn-Huong/front-end-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view their favorite location(s)
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their a list of their favorited location(s)
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-06-19 at 9 15 12 AM](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/a988632a-c8a7-4c1d-8b1d-1ce53abc13c8)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Add CSS styling to favorite location page
- [x] Add a 'div[data-view='favorite-locations'] to HTML
- [x] create container for displaying the list of favorite locations
- [ ] Create a function to render favorite locations
    - [ ] display locations in a list format on mobile and rows on desktop
    - [ ] include the favorite icon to allow unfavoriting.
    - [ ]  display a message if there are no favorite locations
- [ ] Fetch and display favorite locations 
     - [ ] fetch favorite location data from local storage/API
     - [ ] parse the fetched data and pull it when page loads
     - [ ] update data object if the value is empty
     - [ ] use the values from data object for rendering
     - [ ] display data using the render function 

- [ ] Event Handling
     - [ ] Listen for clicks on parent element for all rendered favorite functions
     - [ ] Toggle the favorite location if the favorite icon is clicked

    

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
