### ISSUE TITLE
Feature: User can remove a favorite location

### ISSUE THREAD

**Issue by Katelyn-Ngo** [Katelyn-Huong/front-end-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Remove favorited locations if they wish to
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view and remove their favorite location(s).
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-06-19 at 9 23 14 AM](https://github.com/Katelyn-Huong/front-end-project/assets/167289566/52564e1f-1fb2-471f-b474-4a9a67fbbb4b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Update CSS to show regular heart instead of solid heart when user unfavorite a location
- [ ] Update HTML add a remove icon to each favorite location item
- [ ] Remove Favorite Location Functionality
    - [ ] create a function to handle the removal of a favorite location
    - [ ] update user interface after removal
- [ ] Event Handling
   - [ ] Listen for clicks on the remove icon within the favorite locations section
   - [ ] call the remove favorite location function when the remove icon is clicked
- [ ] make sure data model includes methods for removing a location from the favorites array 
- [ ] - [ ]  Toggle Favorite Location
    - [ ] Listen for clicks on the favorite icon within the favorite locations section
    - [ ] update the visual state of the favorite icon
    - [ ] update data model and local storage
- [ ] update local storage to reflect the removal of the favorite location 
- [ ] Update user interface to show the removal of a the favorite location
- [ ] make sure other favorite locations are still displayed correctly    
-[ ] Update location rendering function
    - [ ] include favorite icon for each rendered location
    - [ ] make sure each rendered location is given a 'data-location-id' attribute 
       to show which location it is 
- [ ]   add functions to add/remove locations from favorites array
- [ ] Toggle Favorite Location
    - [ ] remove the location from list if unfavorited 

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
